name: core_analytics
description: This package provides functions for analysis.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.4

dependencies:
  core_common:
    path: ../common
  firebase_analytics: 11.3.5
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  riverpod_generator: 2.6.5
  test: 1.25.9
  yumemi_lints: 2.2.0

dependency_overrides:
  # workaround
  test_api: 0.7.2
