name: app_mobile
description: "Mobile app"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.5.4
  flutter: 3.24.5

dependencies:
  core_analytics:
    path: ../../core/analytics
  core_authenticator:
    path: ../../core/authenticator
  core_common:
    path: ../../core/common
  core_database:
    path: ../../core/database
  core_datastore:
    path: ../../core/datastore
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  core_network:
    path: ../../core/network
  core_ui:
    path: ../../core/ui
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  envied: 1.1.1
  feature_auth:
    path: ../../feature/auth
  feature_contact:
    path: ../../feature/contact
  feature_feed:
    path: ../../feature/feed
  feature_home:
    path: ../../feature/home
  feature_miscellaneous:
    path: ../../feature/miscellaneous
  feature_onboarding:
    path: ../../feature/onboarding
  feature_settings:
    path: ../../feature/settings
  feature_stopwatch:
    path: ../../feature/stopwatch
  feature_timer:
    path: ../../feature/timer
  firebase_analytics: 11.3.5
  firebase_auth: 5.3.3
  firebase_core: 3.8.0
  firebase_remote_config: 5.1.5
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  go_router: 14.6.1
  hooks_riverpod: 2.6.1
  intl: 0.20.2
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  package_info_plus: 8.1.1
  path_provider: 2.1.5
  riverpod_annotation: 2.6.1
  shared_preferences: 2.3.3
  url_launcher: 6.3.1

dependency_overrides:
  # workaround
  # So, because feature_quest depends on both flutter_test from sdk and riverpod_generator 2.4.2, version solving failed.
  meta: 1.15.0
  # workaround
  # https://stackoverflow.com/questions/77947590/error-the-type-jsobject-cant-be-used-as-supertype-while-deploying-flutter
  web: 0.4.2

dev_dependencies:
  build_runner: 2.4.13
  envied_generator: 1.1.1
  go_router_builder: 2.7.1
  riverpod_generator: 2.6.3
  yumemi_lints: 2.2.0

flutter:
  uses-material-design: true
