name: core_network
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.4

dependencies:
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_network_model:
    path: ../network_model
  dio: 5.9.0
  freezed_annotation: 2.4.4
  retrofit: 4.7.2
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.8.0
  freezed: 2.5.8
  retrofit_generator: 9.7.0
  riverpod_generator: 2.6.3
  yumemi_lints: 2.2.0
