name: core_testing
description: This package provides convenience functions for testing, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.9.3

dependencies:
  core_common:
    path: ../common
  core_model:
    path: ../model
  mocktail: 1.0.4
  riverpod: 2.6.1

dev_dependencies:
  yumemi_lints: 2.2.0
