name: 'Deploy docs'
description: 'Deploy document site for Cloudflare Pages'

inputs:
  project-name:
    description: 'The name of the project'
    required: true
  branch:
    description: 'The branch to deploy'
    required: true
  cloudflare-account-id:
    description: 'The Cloudflare account ID'
    required: true
  cloudflare-api-token:
    description: 'The Cloudflare API token'
    required: true
outputs:
  deployment-url:
    description: 'The URL of the deployment'
    value: ${{ steps.cloudflare-pages.outputs.deployment-url }}

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/mise-action
    - name: mise action
      uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1

    - name: Install deps
      shell: bash
      run: bun install

    - name: Build
      run: bun run build
      shell: bash
      working-directory: ./docs

    # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
      id: cloudflare-pages
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        command: >
          pages deploy ./docs/dist
          --project-name=${{ inputs.project-name }}
          --branch=${{ inputs.branch }}
