name: 'Add lockfiles commit against Renovate'

on:
  pull_request: ~

permissions:
  contents: write
  pull-requests: write

jobs:
  committer:
    runs-on: ubuntu-24.04
    outputs:
      renovate: ${{ steps.check.outputs.renovate }}
    steps:
      - name: Check if last commit
        id: check
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == "renovate[bot]" ]]; then
            echo "renovate=true" >> "$GITHUB_OUTPUT"
          else
            echo "renovate=false" >> "$GITHUB_OUTPUT"
          fi

  changes:
    runs-on: ubuntu-24.04
    outputs:
      bun: ${{ steps.filter.outputs.bun }}
      pub: ${{ steps.filter.outputs.pub }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            bun:
              - '**/package.json'
            pub:
              - '**/pubspec.yaml'

  bun:
    needs:
      - committer
      - changes
    if: >
      needs.committer.outputs.renovate == 'true' &&
      needs.changes.outputs.bun == 'true'
    name: bun.lockb
    uses: ./.github/workflows/wc-bun-lockb.yml
    with:
      gh-app-id: ${{ vars.BOT_APP_ID }}
    secrets:
      gh-app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}

  pub:
    needs:
      - committer
      - changes
    if: >
      needs.committer.outputs.renovate == 'true' &&
      needs.changes.outputs.pub == 'true'
    name: pubspec.lock
    uses: ./.github/workflows/wc-pubspec-locks.yml
    with:
      gh-app-id: ${{ vars.BOT_APP_ID }}
    secrets:
      gh-app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
