name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  catalog:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Build
        run: flutter build web --release
        working-directory: app/catalog

      # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy ./app/catalog/build/web
            --project-name=torchro-app-catalog
            --branch=main
