name: "Check for changes in paths"

on:
  workflow_call:
    outputs:
      action:
        value: ${{ jobs.changes.outputs.action }}
      analyze:
        value: ${{ jobs.changes.outputs.analyze }}
      any:
        value: ${{ jobs.changes.outputs.any }}
      docs:
        value: ${{ jobs.changes.outputs.docs }}
      test:
        value: ${{ jobs.changes.outputs.test }}
      dependencies:
        value: ${{ jobs.changes.outputs.dependencies }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      action: ${{ steps.filter.outputs.action }}
      analyze: ${{ steps.filter.outputs.analyze }}
      any: ${{ steps.filter.outputs.changes != '[]' }}
      docs: ${{ steps.filter.outputs.docs }}
      test: ${{ steps.filter.outputs.test }}
      dependencies: ${{ steps.needs.outputs.dependencies }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            action:
              - '.github/actions/*.yml'
              - '.github/workflows/*.yml'
            analyze:
              - '.github/workflows/checks.yml'
              - '.github/workflows/wc-changes.yml'
              - '.tool-versions'
              - 'melos.yaml'
              - 'apps/**/*'
              - 'core/**/lib/**/*'
              - 'feature/**/lib/**/*'
              - '**/pubspec.*'
            docs:
              - '.github/workflows/checks.yml'
              - '.github/workflows/wc-changes.yml'
              - '**/package.json'
              - 'bun.lockb'
              - 'docs/**/*'
            test:
              - '.github/workflows/checks.yml'
              - '.github/workflows/wc-changes.yml'
              - '.tool-versions'
              - 'melos.yaml'
              - 'apps/**/*'
              - 'core/**/lib/**/*'
              - 'feature/**/lib/**/*'
              - '**/pubspec.*'

      - name: Check for dependencies changes
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: needs
        with:
          script: |
            const changes = ${{ steps.filter.outputs.changes }};

            // 依存関係の解決が必要な変更箇所
            const dependencies = [
              'analyze',
              'test',
            ];
            core.setOutput('dependencies', changes.some(value => dependencies.includes(value)));
