name: "Catalog Preview"

on:
  workflow_call:
    inputs:
      gh-app-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true
      cloudflare-account-id:
        required: true
      cloudflare-api-token:
        required: true

concurrency:
  group: catalog-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

        # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: ${{ inputs.gh-app-id }}
          private-key: ${{ secrets.gh-app-private-key }}

      # https://github.com/marketplace/actions/comment-pull-request
      - uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying torchro-app-catalog with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            :dancer: Now building ${{ github.sha }} ... :dancer:

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment_tag: deploy-catalog-preview
          mode: upsert

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Build
        run: flutter build web --release
        working-directory: app/catalog

      # https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        id: deploy
        with:
          apiToken: ${{ secrets.cloudflare-api-token }}
          accountId: ${{ secrets.cloudflare-account-id }}
          command: >
            pages deploy ./app/catalog/build/web
            --project-name=torchro-app-catalog
            --branch=preview

      # https://github.com/marketplace/actions/comment-pull-request
      - if: steps.deploy.outcome == 'success'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying torchro-app-catalog with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            <table><tr><td><strong>Latest commit:</strong> </td><td>
            ${{ github.sha }} ${{ github.event.pull_request.head.sha && format('(i.e. {0} on {1})', github.event.pull_request.head.sha, 'preview') || '' }}
            </td></tr>
            <tr><td><strong>Status:</strong></td><td>&nbsp;✅&nbsp; Deploy successful!</td></tr>
            <tr><td><strong>Preview URL:</strong></td><td>
            <a href='${{ steps.deploy.outputs.deployment-url }}'>${{ steps.deploy.outputs.deployment-url }}</a>
            </td></tr>
            </table>

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment_tag: deploy-catalog-preview
          mode: recreate

      # https://github.com/marketplace/actions/comment-pull-request
      - if: failure()
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying torchro-app-catalog with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            <table><tr><td><strong>Latest commit:</strong> </td><td>
            ${{ github.sha }}
            </td></tr>
            <tr><td><strong>Status:</strong></td><td>&nbsp;:warning:&nbsp; ${{ steps.deploy.outcome == 'failure' && 'Deploy' || '**Job**' }} failure!</td></tr>
            </table>

            Check the run result and/or Cloudflare Pages.

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment_tag: deploy-catalog-preview
          mode: recreate
